# Generated by Django 4.2.3 on 2023-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_clientes_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articulos',
            new_name='articulo',
        ),
        migrations.RenameModel(
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='pedidos',
            new_name='pedido',
        ),
    ]
